name: tab_router_example
description: tab_router_example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.17.0
  meta: ^1.7.0
  intl: ^0.18.1
  l: ^3.2.0
  path: ^1.8.2
  shared_preferences: ^2.0.16
  tab_router:
    path: packages/tab_router
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.2.1
  build: ^2.0.0
  build_runner: ^2.0.2
  build_test: ^2.0.0
  flutter_gen_runner: any
  pubspec_generator: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/products/1/
    - assets/images/products/2/
    - assets/images/products/3/
    - assets/images/products/4/
    - assets/images/products/5/
    - assets/images/products/6/
    - assets/images/products/7/
    - assets/images/products/8/
    - assets/images/products/9/
    - assets/images/products/10/
    - assets/images/products/11/
    - assets/images/products/12/
    - assets/images/products/13/
    - assets/images/products/14/
    - assets/images/products/15/
    - assets/images/products/16/
    - assets/images/products/17/
    - assets/images/products/18/
    - assets/images/products/19/
    - assets/images/products/20/
    - assets/images/products/21/
    - assets/images/products/22/
    - assets/images/products/23/
    - assets/images/products/24/
    - assets/images/products/25/
    - assets/images/products/26/
    - assets/images/products/27/
    - assets/images/products/28/
    - assets/images/products/29/
    - assets/images/products/30/
    - assets/images/products/31/
    - assets/images/products/32/
    - assets/images/products/33/
    - assets/images/products/34/
    - assets/images/products/35/
    - assets/images/products/36/
    - assets/images/products/37/
    - assets/images/products/38/
    - assets/images/products/39/
    - assets/images/products/40/
    - assets/images/products/41/
    - assets/images/products/42/
    - assets/images/products/43/
    - assets/images/products/44/
    - assets/images/products/45/
    - assets/images/products/46/
    - assets/images/products/47/
    - assets/images/products/48/
    - assets/images/products/49/
    - assets/images/products/50/
    - assets/images/products/51/
    - assets/images/products/52/
    - assets/images/products/53/
    - assets/images/products/54/
    - assets/images/products/55/
    - assets/images/products/56/
    - assets/images/products/57/
    - assets/images/products/58/
    - assets/images/products/59/
    - assets/images/products/60/
    - assets/images/products/61/
    - assets/images/products/62/
    - assets/images/products/63/
    - assets/images/products/64/
    - assets/images/products/65/
    - assets/images/products/66/
    - assets/images/products/67/
    - assets/images/products/68/
    - assets/images/products/69/
    - assets/images/products/70/
    - assets/images/products/71/
    - assets/images/products/72/
    - assets/images/products/73/
    - assets/images/products/74/
    - assets/images/products/75/
    - assets/images/products/76/
    - assets/images/products/77/
    - assets/images/products/78/
    - assets/images/products/79/
    - assets/images/products/80/
    - assets/images/products/81/
    - assets/images/products/82/
    - assets/images/products/83/
    - assets/images/products/84/
    - assets/images/products/85/
    - assets/images/products/86/
    - assets/images/products/87/
    - assets/images/products/88/
    - assets/images/products/89/
    - assets/images/products/90/
    - assets/images/products/91/
    - assets/images/products/92/
    - assets/images/products/93/
    - assets/images/products/94/
    - assets/images/products/95/
    - assets/images/products/96/
    - assets/images/products/97/
    - assets/images/products/98/
    - assets/images/products/99/
    - assets/images/products/100/

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false

flutter_gen:
  output: lib/src/common/constant/
  line_length: 120
