name: tab_router

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-374.1.beta <3.0.0'
  flutter: '>=3.6.0-0.1.pre'

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.2
  platform_info: ^3.2.0

flutter:
  uses-material-design: true